# Streamlit secrets configuration for ezOverThinking
# This file contains sensitive configuration data

# API Configuration
API_BASE_URL = "http://localhost:8000"
API_TIMEOUT = 30

# Authentication (for future use)
JWT_SECRET_KEY = "your-secret-key-here"
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_HOURS = 24

# Database Configuration (if needed)
DATABASE_URL = "postgresql://user:password@localhost:5432/ezoverthinking"

# Redis Configuration (if needed)
REDIS_URL = "redis://localhost:6379"

# External Services (for future use)
OPENAI_API_KEY = "your-openai-api-key-here"
ANALYTICS_API_KEY = "your-analytics-api-key-here"

# Feature Flags
ENABLE_WEBSOCKET = true
ENABLE_ANALYTICS = true
ENABLE_NOTIFICATIONS = true
DEBUG_MODE = false

# UI Configuration
DEFAULT_THEME = "dark"
ENABLE_SOUND_EFFECTS = true
ENABLE_ANIMATIONS = true

# Monitoring
ENABLE_METRICS = true
LOG_LEVEL = "INFO" 